"""add type column

Revision ID: 069ffdf40da8
Revises: 21fa633259ab
Create Date: 2023-11-03 21:17:01.327070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "069ffdf40da8"
down_revision = "21fa633259ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(length=64), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
