"""remove access_token from account table

Revision ID: 0f0be5cd197e
Revises: cf1ffe59d046
Create Date: 2023-11-16 11:32:05.978631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0be5cd197e'
down_revision = 'cf1ffe59d046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['provider', 'providerAccountId'])
        batch_op.drop_column('access_token')
        batch_op.drop_column('id_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_token', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
