"""remove explicit state and country fields from university model

Revision ID: 11beea9988bd
Revises: d3d77d505e49
Create Date: 2023-11-03 11:19:35.683901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11beea9988bd'
down_revision = 'd3d77d505e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_index('ix_universities_country')
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_index('ix_universities_country', ['country'], unique=False)

    # ### end Alembic commands ###
