"""add unique string_id for university model

Revision ID: 21fa633259ab
Revises: 11beea9988bd
Create Date: 2023-11-03 16:54:49.586480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21fa633259ab"
down_revision = "11beea9988bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        # ### These are commands generated to autofill the object_id column
        # ### with a newly-added column.
        batch_op.add_column(
            sa.Column("object_id", sa.String(length=11), nullable=True)
        )

        batch_op.create_unique_constraint(None, ["object_id"])

    # ### end Alembic commands ###

    with op.batch_alter_table("universities", schema=None) as batch_op:
        # Autofill rows with default object_id value whose length is 11 and each
        # character is a random alphanumeric (with uppercase) characters
        batch_op.execute(
            sa.text(
                """
            UPDATE universities
            SET object_id = substr(
                md5(random()::text), 0, 11
            )
            WHERE object_id IS NULL
            """
            )
        )

        batch_op.alter_column("object_id", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("object_id")

    # ### end Alembic commands ###
