"""add active token database

Revision ID: 22b0dd0cb763
Revises: b4d1dfac3102
Create Date: 2023-11-27 11:29:32.571061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b0dd0cb763'
down_revision = 'b4d1dfac3102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=12), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_tokens_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_tokens_token'))

    op.drop_table('active_tokens')
    # ### end Alembic commands ###
