"""create index for university full_name

Revision ID: 2911b29178ab
Revises: 52b730737e11
Create Date: 2023-12-19 14:07:13.093196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2911b29178ab"
down_revision = "52b730737e11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_constraint("universities_full_name_key", type_="unique")

    op.create_index(
        batch_op.f("ix_universities_full_name"),
        "universities",
        [sa.text("""LOWER(full_name) text_pattern_ops""")],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universities_full_name"))
        batch_op.create_unique_constraint(
            "universities_full_name_key", ["full_name"]
        )

    # ### end Alembic commands ###
