"""update metadata for university model

Revision ID: 3832df4d229e
Revises: 53fd93622375
Create Date: 2023-11-01 19:47:13.012502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3832df4d229e"
down_revision = "53fd93622375"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "university_founders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("founder_name", sa.String(length=255), nullable=False),
        sa.Column("biography_link", sa.String(length=255), nullable=True),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["universities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("founder_name", "school_id"),
    )
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("established", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("former_name", sa.String(length=64), nullable=True)
        )
        batch_op.add_column(
            sa.Column("motto", sa.String(length=256), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("motto")
        batch_op.drop_column("former_name")
        batch_op.drop_column("established")

    op.drop_table("university_founders")
    # ### end Alembic commands ###
