"""remove address number from university campus model

Revision ID: 3f57e178746b
Revises: f96805ba3c0a
Create Date: 2023-11-06 15:18:29.730945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f57e178746b"
down_revision = "f96805ba3c0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_campuses", schema=None) as batch_op:
        batch_op.alter_column(
            "address_street",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            "university_campuses_address_number_address_street_country_c_key",
            type_="unique",
        )
        batch_op.create_unique_constraint(
            None, ["address_street", "country_code", "school_short_name"]
        )
        batch_op.drop_column("address_number")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_campuses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "address_number",
                sa.VARCHAR(length=16),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint(
            "university_campuses_address_number_address_street_country_c_key",
            [
                "address_number",
                "address_street",
                "country_code",
                "school_short_name",
            ],
        )
        batch_op.alter_column(
            "address_street",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
