"""add university domain

Revision ID: 7b42a1eed88e
Revises: c07ad29c6bb7
Create Date: 2023-10-30 15:23:21.724418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b42a1eed88e"
down_revision = "c07ad29c6bb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "university_domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_name", sa.String(length=255), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["universities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_constraint("universities_username_key", type_="unique")
        batch_op.drop_column("username")
        batch_op.drop_column("email")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "username", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.create_unique_constraint(
            "universities_username_key", ["username"]
        )

    op.drop_table("university_domains")
    # ### end Alembic commands ###
