"""add columns to university founder relation

Revision ID: 8f550a0de3ba
Revises: b19c3ce986fa
Create Date: 2023-11-07 14:07:20.432481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8f550a0de3ba"
down_revision = "b19c3ce986fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_founders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("first_name", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(
            sa.Column("last_name", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(
            sa.Column("middle_name", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("suffix", sa.String(length=8), nullable=True)
        )
        batch_op.drop_constraint(
            "university_founders_founder_name_school_short_name_key",
            type_="unique",
        )
        batch_op.create_unique_constraint(
            None, ["first_name", "last_name", "school_short_name"]
        )
        batch_op.drop_column("founder_name")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_founders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "founder_name",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint(
            "university_founders_founder_name_school_short_name_key",
            ["founder_name", "school_short_name"],
        )
        batch_op.drop_column("suffix")
        batch_op.drop_column("middle_name")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
