"""empty message

Revision ID: 912e9e1ff978
Revises: 60a19285d647
Create Date: 2023-10-31 15:02:20.048615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "912e9e1ff978"
down_revision = "60a19285d647"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "universities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("full_name"),
    )
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_universities_country"), ["country"], unique=False
        )

    op.create_table(
        "university_domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain_name", sa.String(length=255), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["universities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("university_domains")
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universities_country"))

    op.drop_table("universities")
    # ### end Alembic commands ###
