"""empty message

Revision ID: 9527d02ba370
Revises: 
Create Date: 2023-10-29 23:05:36.290371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9527d02ba370"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("full_name", sa.String(), nullable=False)
        )
        batch_op.add_column(sa.Column("state", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("country", sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ["full_name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("universities", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("country")
        batch_op.drop_column("state")
        batch_op.drop_column("full_name")

    # ### end Alembic commands ###
