"""add constraints to (name, email)

Revision ID: b4d1dfac3102
Revises: 0f0be5cd197e
Create Date: 2023-11-16 20:07:17.667021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4d1dfac3102"
down_revision = "0f0be5cd197e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=256), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=256), nullable=False
        )
        batch_op.drop_index("ix_users_email")
        batch_op.create_index(
            batch_op.f("ix_users_email"), ["email"], unique=False
        )
        batch_op.create_unique_constraint(None, ["email", "name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index("ix_users_email", ["email"], unique=False)
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=256), nullable=True
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=256), nullable=True
        )

    # ### end Alembic commands ###
