"""add created_at for user first sign in

Revision ID: b703b6676255
Revises: 345a83f99da3
Create Date: 2023-12-11 20:27:45.547757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b703b6676255"
down_revision = "345a83f99da3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )

    connection = op.get_bind()

    connection.execute(
        sa.text(
            """
                UPDATE users
                SET created_at = NOW()
                WHERE created_at IS NULL
            """
        )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
