"""alter updated_at to modified_at in department model

Revision ID: cc6d83c274d5
Revises: d445fca8cd5d
Create Date: 2023-12-20 22:57:36.564553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cc6d83c274d5"
down_revision = "d445fca8cd5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "modified_at",
                sa.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )
        batch_op.drop_index("ix_departments_name")
        batch_op.create_index(
            batch_op.f("ix_departments_name"), ["name"], unique=False
        )
        batch_op.drop_index("ix_departments_type")
        batch_op.create_index(
            batch_op.f("ix_departments_type"), ["type"], unique=False
        )
        batch_op.drop_column("updated_at")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "updated_at",
                postgresql.TIMESTAMP(timezone=True),
                server_default=sa.text("now()"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_departments_type"))
        batch_op.create_index(
            "ix_departments_type", [sa.text("lower(type::text)")], unique=False
        )
        batch_op.drop_index(batch_op.f("ix_departments_name"))
        batch_op.create_index(
            "ix_departments_name", [sa.text("lower(name::text)")], unique=False
        )
        batch_op.drop_column("modified_at")

    # ### end Alembic commands ###
