"""add university campus model

Revision ID: d3d77d505e49
Revises: f77eed2a133c
Create Date: 2023-11-02 16:57:28.345071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3d77d505e49"
down_revision = "f77eed2a133c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "university_campuses",
        sa.Column(
            "address_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("address_number", sa.String(length=16), nullable=False),
        sa.Column("address_street", sa.String(length=64), nullable=False),
        sa.Column("address_city", sa.String(length=64), nullable=False),
        sa.Column("address_state", sa.String(length=64), nullable=False),
        sa.Column("address_zip_code", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["countries.alpha2"],
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["universities.id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
        sa.UniqueConstraint(
            "address_number", "address_street", "country_code", "school_id"
        ),
    )
    with op.batch_alter_table("university_campuses", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_university_campuses_school_id"),
            ["school_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_campuses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_university_campuses_school_id"))

    op.drop_table("university_campuses")
    # ### end Alembic commands ###
