"""add index for department name and type

Revision ID: d445fca8cd5d
Revises: d82ac9ef7cac
Create Date: 2023-12-20 15:36:01.910753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d445fca8cd5d"
down_revision = "d82ac9ef7cac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(length=32), nullable=False)
        )
        batch_op.add_column(
            sa.Column("special_name", sa.String(length=128), nullable=True)
        )

    op.create_index(
        batch_op.f("ix_departments_name"),
        "departments",
        [sa.text("""LOWER(name) text_pattern_ops""")],
    )

    op.create_index(
        batch_op.f("ix_departments_type"),
        "departments",
        [sa.text("""LOWER(type) text_pattern_ops""")],
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_type"))
        batch_op.drop_index(batch_op.f("ix_departments_name"))
        batch_op.drop_column("special_name")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
