"""update iso639_1 for standard language code in university domain

Revision ID: d6b078380d36
Revises: 310cab0673ee
Create Date: 2023-11-05 18:48:12.349485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6b078380d36"
down_revision = "310cab0673ee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_domains", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("iso639_1", sa.String(length=8), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("university_domains", schema=None) as batch_op:
        batch_op.drop_column("iso639_1")

    # ### end Alembic commands ###
