"""update cascade on university

Revision ID: eace13343791
Revises: 7ceb28afd876
Create Date: 2023-12-15 15:07:26.894342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eace13343791'
down_revision = '7ceb28afd876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('courses_school_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'universities', ['school_id'], ['short_name'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('courses_school_id_fkey', 'universities', ['school_id'], ['short_name'])

    # ### end Alembic commands ###
