"""add type column for university domain relations

Revision ID: f96805ba3c0a
Revises: d6b078380d36
Create Date: 2023-11-05 19:58:50.165978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96805ba3c0a'
down_revision = 'd6b078380d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=16), server_default='TLD', nullable=False))
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('university_domains', schema=None) as batch_op:
        batch_op.alter_column('domain_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
